---
title: "p8105_hw4_problem_1"
author: "Jiaqi Li"
date: "10/25/2017"
output: html_document
---
```{r}
library(janitor)
library(tidyr)
library(dplyr)
library(tidyverse)
library(ggridges)
library(DT)
```

### Problem 1
```{r Problem_1}
## Loading data and cleaning data
pups_data <- readr::read_csv("FAS_pups.csv") %>% 
  clean_names() %>% 
  gather(key = developmental_landmarks, value = post_natal_days, pd_ears:pd_walk) %>% 
  mutate(developmental_landmarks = recode(developmental_landmarks, "pd_ears" = "ears", "pd_eyes" = "eyes", "pd_pivot" = "pivot", "pd_walk" = "walk")) %>% 
  drop_na() 

```

```{r}
pups_data %>% 
  ggplot(aes(x = post_natal_days, y = developmental_landmarks, color = developmental_landmarks)) +
  geom_density_ridges(scale = .85)
```

```{r}
x <- pups_data %>% 
  group_by(developmental_landmarks) %>% 
  summarise(mean_deve = mean(post_natal_days))
datatable(x)
```

According to the plot and table above, we can conclude that the mean post-natal days for eyes is obviously higher than other three. The mean post-natal days for ears is the lowest among four. And also, compared to the post-natals days for pivot, that for walk is a little bit higher.